=== Janonym98/VU2RVC_XMLGyak/XMLTaskVU2RVC/XML/XSDVU2RVC.xsd
<?xml version="1.0" encoding="utf-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="szobeli">
        <xs:complexType>
            <xs:sequence>
                <xs:choice maxOccurs="unbounded">
                    <xs:element name="tanulo" type="tanulo_type"/>
                    <xs:element name="szobeli_erettsegi" type="szobeli_erettsegi_type"/>
                    <xs:element name="tantargy" type="tantargy_type"/>
                    <xs:element name="elnok" type="elnok_type"/>
                    <xs:element name="tanar" type="tanar_type"/>
                    <xs:element name="bizonyitvany" type="bizonyitvany_type"/>
                </xs:choice>
            </xs:sequence>
        </xs:complexType>
        <xs:key name="tantargy_ID">
        <xs:selector xpath=".//tantargy" />
        <xs:field xpath="@id" />
    </xs:key>
    <xs:keyref name="tantargy_IDref" refer="tantargy_ID">
        <xs:selector xpath=".//szobeli_erettsegi" />
        <xs:field xpath="@tantargy_ID" />
    </xs:keyref>

    <xs:key name="tanulo_ID">
        <xs:selector xpath=".//tanulo" />
        <xs:field xpath="@id" />
    </xs:key>
    <xs:keyref name="tanulo_IDref" refer="tanulo_ID">
        <xs:selector xpath=".//szobeli_erettsegi | .//bizonyitvany" />
        <xs:field xpath="@tanulo_ID" />
    </xs:keyref>

    <xs:key name="tanar_ID">
        <xs:selector xpath=".//tanar" />
        <xs:field xpath="@id" />
    </xs:key>
    <xs:keyref name="tanar_IDref" refer="tanar_ID">
        <xs:selector xpath=".//tantargy" />
        <xs:field xpath="@tanar_ID" />
    </xs:keyref>

    <xs:key name="szobeli_erettsegi_ID">
        <xs:selector xpath=".//szobeli_erettsegi" />
        <xs:field xpath="@id" />
    </xs:key>
    <xs:keyref name="szobeli_erettsegi_IDref" refer="szobeli_erettsegi_ID">
        <xs:selector xpath=".//elnok" />
        <xs:field xpath="@szobeli_erettsegi_ID" />
    </xs:keyref>
    </xs:element>
    <xs:complexType name="tanulo_type">
        <xs:sequence>
            <xs:element name="vezeteknev" type="xs:string"/>
            <xs:element name="utonev" type="xs:string"/>
            <xs:element name="szuletesi_ev" type="xs:integer"/>
            <xs:element name="lakhely" type="xs:string"/>
            <xs:element name="iskola" type="xs:string"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:unsignedByte"/>
    </xs:complexType>
    <xs:complexType name="szobeli_erettsegi_type">
        <xs:sequence>
            <xs:element name="helyszin" type="xs:string"/>
            <xs:element name="szint" type="xs:string"/>
            <xs:element name="idopont" type="xs:date"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:unsignedByte"/>
        <xs:attribute name="tanulo_ID" type="xs:unsignedByte"/>
        <xs:attribute name="tantargy_ID" type="xs:unsignedByte"/>
    </xs:complexType>
    <xs:complexType name="tantargy_type">
        <xs:sequence>
            <xs:element name="nev" type="xs:string"/>
            <xs:element name="tetel" type="xs:integer"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:unsignedByte"/>
        <xs:attribute name="tanar_ID" type="xs:unsignedByte"/>
    </xs:complexType>
    <xs:complexType name="elnok_type">
        <xs:sequence>
            <xs:element name="vezeteknev" type="xs:string"/>
            <xs:element name="utonev" type="xs:string"/>
            <xs:element name="iskola" type="xs:string"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:unsignedByte"/>
        <xs:attribute name="szobeli_ID" type="xs:unsignedByte"/>
    </xs:complexType>
    <xs:complexType name="tanar_type">
        <xs:sequence>
            <xs:element name="vezeteknev" type="xs:string"/>
            <xs:element name="utonev" type="xs:string"/>
            <xs:element name="tanitott_targy" type="xs:string"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:unsignedByte"/>
    </xs:complexType>
    <xs:complexType name="bizonyitvany_type">
        <xs:sequence>
            <xs:element name="szint" type="xs:string"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:unsignedByte"/>
        <xs:attribute name="tanulo_ID" type="xs:unsignedByte"/>
    </xs:complexType>

</xs:schema>

=== Janonym98/VU2RVC_XMLGyak/XMLTaskVU2RVC/XML/XMLVU2RVC.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<szobeli xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="XSDVU2RVC.xsd">
    <tanulo id="01">
        <vezeteknev>Hurka</vezeteknev>
        <utonev>Gyurka</utonev>
        <szuletesi_ev>1999</szuletesi_ev>
        <lakhely>Miskolc</lakhely>
        <iskola>Bláthy</iskola>
    </tanulo>
    <tanulo id="02">
        <vezeteknev>Bármi</vezeteknev>
        <utonev>Áron</utonev>
        <szuletesi_ev>1995</szuletesi_ev>
        <lakhely>Miskolc</lakhely>
        <iskola>Diósgyőri</iskola>
    </tanulo>
    <tanulo id="03">
        <vezeteknev>Ebéd</vezeteknev>
        <utonev>Elek</utonev>
        <szuletesi_ev>2001</szuletesi_ev>
        <lakhely>Miskolc</lakhely>
        <iskola>Avasi</iskola>
    </tanulo>
    <szobeli_erettsegi id="01" tantargy_ID="01" tanulo_ID="01">
        <helyszin>Bláthy</helyszin>
        <szint>közép</szint>
        <idopont>2016-06-15</idopont>
    </szobeli_erettsegi>
    <szobeli_erettsegi id="02" tantargy_ID="02" tanulo_ID="02">
        <helyszin>Fényi</helyszin>
        <szint>emelt</szint>
        <idopont>2018-06-19</idopont>
    </szobeli_erettsegi>
    <szobeli_erettsegi id="03" tantargy_ID="03" tanulo_ID="03">
        <helyszin>Földes</helyszin>
        <szint>közép</szint>
        <idopont>2012-07-01</idopont>
    </szobeli_erettsegi>
    <tantargy id="01" tanar_ID="01">
        <nev>angol</nev>
        <tetel>12</tetel>
    </tantargy>
    <tantargy id="02" tanar_ID="03">
        <nev>Történelem</nev>
        <tetel>6</tetel>
    </tantargy>
    <tantargy id="03" tanar_ID="02">
        <nev>Informatika</nev>
        <tetel>8</tetel>
    </tantargy>
    <elnok id="01" szobeli_ID="01">
        <vezeteknev>Dil</vezeteknev>
        <utonev>Emma</utonev>
        <iskola>Zrínyi</iskola>
    </elnok>
    <elnok id="02" szobeli_ID="02">
        <vezeteknev>Para</vezeteknev>
        <utonev>Zita</utonev>
        <iskola>Diósgyőri</iskola>
    </elnok>
    <elnok id="03" szobeli_ID="03">
        <vezeteknev>Riz</vezeteknev>
        <utonev>Ottó</utonev>
        <iskola>Avasi</iskola>
    </elnok>
    <tanar id="01">
        <vezeteknev>Kala</vezeteknev>
        <utonev>Pál</utonev>
        <tanitott_targy>angol</tanitott_targy>
    </tanar>
    <tanar id="02">
        <vezeteknev>Major</vezeteknev>
        <utonev>Anna</utonev>
        <tanitott_targy>Informatika</tanitott_targy>
    </tanar>
    <tanar id="03">
        <vezeteknev>Fejet</vezeteknev>
        <utonev>Lenke</utonev>
        <tanitott_targy>Történelem</tanitott_targy>
    </tanar>
    <bizonyitvany id="01" tanulo_ID="01">
        <szint>közép</szint>
    </bizonyitvany>
    <bizonyitvany id="02" tanulo_ID="02">
        <szint>emelt</szint>
    </bizonyitvany>
    <bizonyitvany id="03" tanulo_ID="03">
        <szint>közép</szint>
    </bizonyitvany>
</szobeli>
